#!/bin/bash
#
#	/etc/rc.d/init.d/carbon
#
# Starts the carbon daemon
#
# description: Startup the carbon daemon to roll up statsd messages
# processname: carbon

### BEGIN INIT INFO
# Provides: carbon
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the carbon daemon
# Description: Carbon rolls up statsd messages for whisper
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/carbon ]; then
		echo -n $"Starting carbon daemon: "	
	    daemon /opt/graphite/bin/carbon-cache.py start
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/carbon
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping carbon daemon: "
	killproc /opt/graphite/bin/carbon-cache.py
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/carbon
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/carbon ]; then
	    restart
	fi
	;;
status)
	status acpid
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
	RETVAL=2
esac

exit $RETVAL
