#!/bin/bash
#
#    /etc/rc.d/init.d/pencil
#
# Starts the pencil daemon
#
# description: Startup the pencil daemon to roll up statsd messages
# processname: pencil

### BEGIN INIT INFO
# Provides: pencil
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the pencil daemon
# Description: pencil rolls up statsd messages for whisper
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

#
# See how we were called.
#

start() {
    # Check if it is already running
    echo -n $"Starting pencil daemon: "    
    daemon /usr/lib/ruby/gems/1.8/gems/pencil-0.2.10/bin/pencil --config-dir=/opt/pencil/config &
    touch /var/lock/subsys/pencil
    echo
    return 0
}

stop() {
    echo -n $"Stopping pencil daemon: "
    killproc /usr/lib/ruby/gems/1.8/gems/pencil-0.2.10/bin/pencil
    rm -f /var/lock/subsys/pencil
    echo
    return 0
}


restart() {
    stop
    start
}    

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
reload)
    echo "$0: Unimplemented feature."
    RETVAL=3
    ;;
force-reload)
    echo "$0: Unimplemented feature."
    RETVAL=3
    ;;
restart)
    restart
    ;;
condrestart)
    if [ -f /var/lock/subsys/carbon ]; then
        restart
    fi
    ;;
status)
    status acpid
    RETVAL=$?
    ;;
*)
    echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
    RETVAL=2
esac

exit $RETVAL
