#!/bin/bash
#
#	/etc/rc.d/init.d/statsd
#
# Starts the statsd daemon
#
# description: Startup the statsd daemon to roll up statsd messages
# processname: statsd

### BEGIN INIT INFO
# Provides: statsd
# Required-Start: $syslog $local_fs
# Required-Stop: $syslog $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop the statsd daemon
# Description: Carbon rolls up statsd messages for whisper
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/statsd ]; then
		echo -n $"Starting statsd daemon: "	
	    daemon /usr/lib/ruby/gems/1.8/bin/statsd --output=tcp://localhost:2003 2>&1 &
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/statsd
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping statsd daemon: "
	killproc /usr/lib/ruby/gems/1.8/bin/statsd
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/statsd
	echo
    return $RETVAL
}


restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
force-reload)
	echo "$0: Unimplemented feature."
	RETVAL=3
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/statsd ]; then
	    restart
	fi
	;;
status)
	status acpid
	RETVAL=$?
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload}"
	RETVAL=2
esac

exit $RETVAL
